name: Java Build with Maven and Test

on:
  push:
    branches:
      - main  # Değişiklik yapıldığında main (varsayılan) dalında çalıştır
  pull_request:
    branches:
      - main  # Pull isteği yapıldığında main (varsayılan) dalında çalıştır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn package
